[tool.poetry]
name = "streamlit-tool"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.9"
streamlit = "^1.48.0"
# add other dependencies here if needed

# Add this line to disable packaging the current project
package-mode = false
